apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume-nexus
  namespace: nexus
spec:
  capacity:
    storage: 400Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gce-pd-storage
  gcePersistentDisk:
    pdName: nexus-test-disk
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        # failure-domain.beta.kubernetes.io/zone should be used prior to 1.21
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - europe-west4-b
          - europe-west4-c
