apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce-pd
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gce-pd-storage
  resources:
    requests:
      storage: 30Gi
